// Generated by CoffeeScript 1.6.3
(function() {
  var Tracer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Tracer = (function() {
    function Tracer(log, stats, opts) {
      this.measure = __bind(this.measure, this);
      this.stop = __bind(this.stop, this);
      this.prefix = opts.service_name;
      this.log = log;
      this.stats = stats;
      this.times = {};
    }

    Tracer.prototype.trace = function(label, message, object) {
      this.log.error(message, object);
      return this.stats.inc("" + this.prefix + "." + label);
    };

    Tracer.prototype.error = function(label, message, err) {
      return this.trace("" + label + ".error", message, err);
    };

    Tracer.prototype.start = function(key) {
      this.times[key] = new Date();
      return key;
    };

    Tracer.prototype.stop = function(key) {
      this._timing(key, this.times[key]);
      return delete this.times[key];
    };

    Tracer.prototype.measure = function(key, fn) {
      var start;
      start = new Date();
      fn();
      return this._timing(key, start);
    };

    Tracer.prototype._timing = function(key, start) {
      var timing;
      timing = new Date() - start;
      this.stats.timing("" + this.prefix + "." + key + ".time", timing);
      return this.log.debug("Timing of " + this.prefix + "." + key + ".time: " + timing);
    };

    return Tracer;

  })();

  module.exports = Tracer;

}).call(this);
